name = "rust-oauth2-admin-api"
main = "build/worker/shim.mjs"
compatibility_date = "2024-12-16"
kv_namespaces = [
  { binding = "CLIENTS", id = "976f61e6c01c4454bd3c6e03a7922995" },
]

[build]
command = "cargo install -q worker-build && worker-build --release"
